import type { Bounty } from "./types";

export const MOCK_BOUNTIES: Bounty[] = [
  {
    id: "b1",
    title: "Fix authentication bypass vulnerability",
    description:
      "Investigate and patch the reported authentication bypass in the OAuth2 flow that allows unauthorized access to protected endpoints.",
    status: "active",
    reward: 2500,
    currency: "USD",
    tags: ["security", "backend", "bug"],
    tasks: [
      { id: "t1", title: "Reproduce the vulnerability", completed: true },
      { id: "t2", title: "Identify root cause", completed: true },
      { id: "t3", title: "Implement patch", completed: false },
      { id: "t4", title: "Write regression tests", completed: false },
    ],
    hunters: [
      { id: "h1", name: "Alex Rivers", avatar: "" },
      { id: "h2", name: "Sam Chen", avatar: "" },
      { id: "h3", name: "Priya Patel", avatar: "" },
      { id: "h4", name: "Jordan Lee", avatar: "" },
      { id: "h5", name: "Casey Kim", avatar: "" },
    ],
    submittedResponses: 3,
    views: 842,
    createdAt: "2026-03-01",
    deadline: "2026-03-20",
    difficulty: "hard",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "b2",
    title: "Redesign user dashboard with analytics",
    description:
      "Create a modern, responsive dashboard that displays user engagement metrics, charts, and real-time statistics.",
    status: "active",
    reward: 1800,
    currency: "USD",
    tags: ["design", "frontend", "feature"],
    tasks: [
      { id: "t5", title: "Design wireframes", completed: true },
      { id: "t6", title: "Implement chart components", completed: false },
      { id: "t7", title: "Add responsive layout", completed: false },
    ],
    hunters: [
      { id: "h6", name: "Morgan Wright", avatar: "" },
      { id: "h7", name: "Riley Davis", avatar: "" },
      { id: "h8", name: "Jamie Foster", avatar: "" },
    ],
    submittedResponses: 2,
    views: 1256,
    createdAt: "2026-03-05",
    deadline: "2026-03-25",
    difficulty: "medium",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "b3",
    title: "Implement AI-powered code review bot",
    description:
      "Build an intelligent code review assistant that automatically analyzes pull requests and suggests improvements.",
    status: "scheduled",
    reward: 5000,
    currency: "USD",
    tags: ["ai", "devops", "feature"],
    tasks: [
      { id: "t8", title: "Set up LLM integration", completed: false },
      { id: "t9", title: "Build PR webhook handler", completed: false },
      { id: "t10", title: "Create comment engine", completed: false },
      { id: "t11", title: "Add configuration panel", completed: false },
      { id: "t12", title: "Testing & QA", completed: false },
    ],
    hunters: [
      { id: "h9", name: "Taylor Brooks", avatar: "" },
    ],
    submittedResponses: 0,
    views: 2340,
    createdAt: "2026-03-10",
    deadline: "2026-04-15",
    startsAt: "2026-03-18",
    difficulty: "expert",
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "b4",
    title: "Optimize database query performance",
    description:
      "Profile and optimize slow SQL queries causing timeouts on the reports page. Target sub-200ms response times.",
    status: "closed",
    reward: 1200,
    currency: "USD",
    tags: ["performance", "backend", "bug"],
    tasks: [
      { id: "t13", title: "Profile slow queries", completed: true },
      { id: "t14", title: "Add missing indexes", completed: true },
      { id: "t15", title: "Refactor N+1 queries", completed: true },
    ],
    hunters: [
      { id: "h10", name: "Drew Martinez", avatar: "" },
      { id: "h11", name: "Avery Thompson", avatar: "" },
    ],
    submittedResponses: 5,
    views: 678,
    createdAt: "2026-02-15",
    deadline: "2026-03-01",
    difficulty: "medium",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "b5",
    title: "Build mobile push notification system",
    description:
      "Design and implement a cross-platform push notification system supporting iOS and Android with rich media.",
    status: "active",
    reward: 3200,
    currency: "USD",
    tags: ["mobile", "backend", "feature"],
    tasks: [
      { id: "t16", title: "Set up Firebase Cloud Messaging", completed: true },
      { id: "t17", title: "Implement notification scheduler", completed: true },
      { id: "t18", title: "Add rich media support", completed: false },
      { id: "t19", title: "Build preferences UI", completed: false },
    ],
    hunters: [
      { id: "h12", name: "Quinn Phillips", avatar: "" },
      { id: "h13", name: "Sage Anderson", avatar: "" },
      { id: "h14", name: "Rowan Blake", avatar: "" },
      { id: "h15", name: "Harper Collins", avatar: "" },
      { id: "h16", name: "Emery Jackson", avatar: "" },
      { id: "h17", name: "Skyler Reed", avatar: "" },
      { id: "h18", name: "Finley Green", avatar: "" },
    ],
    submittedResponses: 4,
    views: 1890,
    createdAt: "2026-03-03",
    deadline: "2026-03-30",
    difficulty: "hard",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "b6",
    title: "Write API documentation with OpenAPI spec",
    description:
      "Document all public API endpoints using OpenAPI 3.0 specification with examples and SDKs generation.",
    status: "closed",
    reward: 800,
    currency: "USD",
    tags: ["documentation", "backend"],
    tasks: [
      { id: "t20", title: "Audit existing endpoints", completed: true },
      { id: "t21", title: "Write OpenAPI YAML", completed: true },
      { id: "t22", title: "Generate SDK stubs", completed: true },
      { id: "t23", title: "Create usage examples", completed: true },
    ],
    hunters: [
      { id: "h19", name: "Blake Turner", avatar: "" },
    ],
    submittedResponses: 1,
    views: 345,
    createdAt: "2026-02-01",
    deadline: "2026-02-28",
    difficulty: "easy",
    image: "https://images.unsplash.com/photo-1618365908648-e71bd5716cba?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "b7",
    title: "Implement smart contract audit tooling",
    description:
      "Build automated analysis tools for detecting common vulnerabilities in Solidity smart contracts.",
    status: "scheduled",
    reward: 7500,
    currency: "USD",
    tags: ["blockchain", "security", "ai"],
    tasks: [
      { id: "t24", title: "Define vulnerability patterns", completed: false },
      { id: "t25", title: "Build AST parser", completed: false },
      { id: "t26", title: "Implement rule engine", completed: false },
      { id: "t27", title: "Create report generator", completed: false },
    ],
    hunters: [],
    submittedResponses: 0,
    views: 4120,
    createdAt: "2026-03-12",
    deadline: "2026-05-01",
    startsAt: "2026-03-25",
    difficulty: "expert",
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "b8",
    title: "Add dark mode to marketing site",
    description:
      "Implement a theme toggle and dark color scheme for the public marketing website with smooth transitions.",
    status: "active",
    reward: 600,
    currency: "USD",
    tags: ["frontend", "design"],
    tasks: [
      { id: "t28", title: "Define dark palette", completed: true },
      { id: "t29", title: "Add CSS variables", completed: true },
      { id: "t30", title: "Build theme toggle", completed: false },
    ],
    hunters: [
      { id: "h20", name: "Dakota Nguyen", avatar: "" },
      { id: "h21", name: "River Scott", avatar: "" },
    ],
    submittedResponses: 1,
    views: 520,
    createdAt: "2026-03-08",
    deadline: "2026-03-22",
    difficulty: "easy",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800",
  },
];
